In [4]:
import pandas as pd
df= pd.read_excel("D:\\edge downlode\\education_dataset.xlsx")
df

,Student_ID,Student_Name,Gender,Age,Grade_Level,Department,City,Attendance_%,Math_Score,Science_Score,English_Score,History_Score,Avg_Score,Grade,Study_Hours/Week,Internet_Access,Parent_Education,Scholarship,Extracurricular,Pass/Fail
0,S001,Aarav Kumar,Male,16,10th,Science,Chennai,92,88,85,90,78,NaN,NaN,18,Yes,Graduate,Yes,Yes,NaN
1,S002,Priya Sharma,Female,17,11th,Commerce,Mumbai,87,72,80,68,85,NaN,NaN,14,Yes,Post-Graduate,No,No,NaN
2,S003,Rohit Mehta,Male,15,9th,Science,Delhi,75,65,70,60,72,NaN,NaN,10,No,High School,No,Yes,NaN
3,S004,Sneha Patel,Female,16,10th,Arts,Ahmedabad,95,55,60,85,90,NaN,NaN,12,Yes,Graduate,Yes,Yes,NaN
4,S005,Vikram Singh,Male,17,11th,Science,Jaipur,80,90,88,85,70,NaN,NaN,20,Yes,Post-Graduate,Yes,No,NaN
5,S006,Ananya Iyer,Female,18,12th,Science,Bangalore,98,95,92,88,96,NaN,NaN,22,Yes,Post-Graduate,Yes,Yes,NaN
6,S007,Karan Nair,Male,15,9th,Arts,Kochi,60,50,55,70,65,NaN,NaN,8,No,High School,No,No,NaN
7,S008,Divya Reddy,Female,16,10th,Commerce,Hyderabad,88,68,75,72,80,NaN,NaN,13,Yes,Graduate,No,Yes,NaN
8,S009,Arjun Joshi,Male,17,11th,Science,Pune,70,78,74,70,65,NaN,NaN,15,Yes,Graduate,No,No,NaN
9,S010,Meera Pillai,Female,18,12th,Commerce,Trivandrum,93,60,85,78,88,NaN,NaN,16,Yes,Post-Graduate,Yes,Yes,NaN
10,S011,Siddharth Roy,Male,16,10th,Science,Kolkata,82,80,76,74,79,NaN,NaN,17,Yes,Graduate,No,Yes,NaN
11,S012,Lakshmi Rao,Female,15,9th,Arts,Chennai,78,55,60,80,75,NaN,NaN,11,No,High School,No,No,NaN
12,S013,Nikhil Desai,Male,17,11th,Commerce,Surat,65,62,70,58,66,NaN,NaN,9,No,High School,No,No,NaN
13,S014,Pooja Verma,Female,18,12th,Science,Lucknow,90,88,84,90,86,NaN,NaN,19,Yes,Post-Graduate,Yes,Yes,NaN
14,S015,Rahul Gupta,Male,16,10th,Arts,Kanpur,55,48,52,65,58,NaN,NaN,7,No,High School,No,No,NaN
15,S016,Ishaan Malhotra,Male,17,11th,Science,Delhi,85,92,89,84,80,NaN,NaN,21,Yes,Post-Graduate,Yes,Yes,NaN
16,S017,Tanvi Bhatt,Female,15,9th,Commerce,Vadodara,72,60,68,62,70,NaN,NaN,10,Yes,Graduate,No,No,NaN
17,S018,Aditya Pandey,Male,18,12th,Science,Varanasi,68,74,70,65,72,NaN,NaN,14,No,Graduate,No,Yes,NaN
18,S019,Ritu Saxena,Female,16,10th,Arts,Agra,84,58,62,82,80,NaN,NaN,12,Yes,High School,No,Yes,NaN
19,S020,Manish Tiwari,Male,17,11th,Commerce,Bhopal,77,65,72,60,75,NaN,NaN,13,No,Graduate,No,No,NaN
20,S021,Kavya Menon,Female,18,12th,Science,Coimbatore,96,94,91,89,95,NaN,NaN,23,Yes,Post-Graduate,Yes,Yes,NaN
21,S022,Harsh Agarwal,Male,15,9th,Arts,Indore,58,45,50,68,55,NaN,NaN,6,No,High School,No,No,NaN
22,S023,Swati Mishra,Female,16,10th,Science,Nagpur,81,79,77,75,82,NaN,NaN,16,Yes,Graduate,Yes,No,NaN
23,S024,Varun Kapoor,Male,17,11th,Commerce,Chandigarh,74,66,71,63,76,NaN,NaN,12,Yes,Graduate,No,Yes,NaN
24,S025,Deepa Nambiar,Female,18,12th,Arts,Kochi,89,62,70,92,88,NaN,NaN,15,Yes,Post-Graduate,No,Yes,NaN
25,S026,Akash Srivastava,Male,16,10th,Science,Allahabad,66,72,68,64,70,NaN,NaN,11,No,Graduate,No,No,NaN
26,S027,Shruti Kulkarni,Female,15,9th,Commerce,Nashik,76,58,65,60,72,NaN,NaN,9,Yes,High School,No,No,NaN
27,S028,Piyush Bansal,Male,17,11th,Science,Faridabad,83,86,84,80,82,NaN,NaN,18,Yes,Graduate,Yes,Yes,NaN
28,S029,Neha Chaudhary,Female,18,12th,Arts,Meerut,91,55,68,94,90,NaN,NaN,14,No,Post-Graduate,Yes,Yes,NaN
29,S030,Sameer Khan,Male,16,10th,Commerce,Lucknow,70,60,68,58,72,NaN,NaN,10,No,High School,No,No,NaN
30,S031,Anjali Subramaniam,Female,17,11th,Science,Madurai,88,90,87,85,89,NaN,NaN,20,Yes,Post-Graduate,Yes,Yes,NaN
31,S032,Rajesh Naidu,Male,15,9th,Arts,Vizag,62,50,55,72,60,NaN,NaN,8,No,High School,No,No,NaN
32,S033,Preeti Sharma,Female,18,12th,Commerce,Gurgaon,94,70,82,75,92,NaN,NaN,16,Yes,Graduate,Yes,Yes,NaN
33,S034,Yash Chauhan,Male,16,10th,Science,Noida,79,82,78,76,80,NaN,NaN,15,Yes,Graduate,No,Yes,NaN
34,S035,Bhavna Soni,Female,17,11th,Arts,Rajkot,85,56,65,90,84,NaN,NaN,13,Yes,High School,No,Yes,NaN
35,S036,Kartik Bajaj,Male,18,12th,Science,Amritsar,73,76,74,70,75,NaN,NaN,12,No,Graduate,No,No,NaN
36,S037,Riya Jain,Female,15,9th,Commerce,Jodhpur,80,62,72,65,78,NaN,NaN,11,Yes,Graduate,No,No,NaN
37,S038,Suresh Pillai,Male,16,10th,Arts,Thrissur,67,48,54,74,65,NaN,NaN,9,No,High School,No,No,NaN
38,S039,Nandini Ghosh,Female,17,11th,Science,Kolkata,92,88,86,84,91,NaN,NaN,21,Yes,Post-Graduate,Yes,Yes,NaN
39,S040,Abhishek Pandey,Male,18,12th,Commerce,Patna,76,64,72,60,78,NaN,NaN,13,No,Graduate,No,Yes,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Student_ID        40 non-null     object
 1   Student_Name      40 non-null     object
 2   Gender            40 non-null     object
 3   Age               40 non-null     int64
 4   Grade_Level       40 non-null     object
 5   Department        40 non-null     object
 6   City              40 non-null     object
 7   Attendance_%      40 non-null     int64
 8   Math_Score        40 non-null     int64
 9   Science_Score     40 non-null     int64
 10  English_Score     40 non-null     int64
 11  History_Score     40 non-null     int64
 12  Avg_Score         0 non-null      float64
 13  Grade             0 non-null      float64
 14  Study_Hours/Week  40 non-null     int64
 15  Internet_Access   40 non-null     object
 16  Parent_Education  40 non-null     object
 17  Scholarship       40 non-null     object
 18  Extracurricular   40 non-null     object
 19  Pass/Fail         0 non-null      float64
dtypes: float64(3), int64(7), object(10)
memory usage: 6.4+ KB

In [6]:
print(df.isnull().sum())

Student_ID           0
Student_Name         0
Gender               0
Age                  0
Grade_Level          0
Department           0
City                 0
Attendance_%         0
Math_Score           0
Science_Score        0
English_Score        0
History_Score        0
Avg_Score           40
Grade               40
Study_Hours/Week     0
Internet_Access      0
Parent_Education     0
Scholarship          0
Extracurricular      0
Pass/Fail           40
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df=df.drop_duplicates()

In [9]:
df.fillna(df.mean(numeric_only=True), inplace=True)
df

,Student_ID,Student_Name,Gender,Age,Grade_Level,Department,City,Attendance_%,Math_Score,Science_Score,English_Score,History_Score,Avg_Score,Grade,Study_Hours/Week,Internet_Access,Parent_Education,Scholarship,Extracurricular,Pass/Fail
0,S001,Aarav Kumar,Male,16,10th,Science,Chennai,92,88,85,90,78,NaN,NaN,18,Yes,Graduate,Yes,Yes,NaN
1,S002,Priya Sharma,Female,17,11th,Commerce,Mumbai,87,72,80,68,85,NaN,NaN,14,Yes,Post-Graduate,No,No,NaN
2,S003,Rohit Mehta,Male,15,9th,Science,Delhi,75,65,70,60,72,NaN,NaN,10,No,High School,No,Yes,NaN
3,S004,Sneha Patel,Female,16,10th,Arts,Ahmedabad,95,55,60,85,90,NaN,NaN,12,Yes,Graduate,Yes,Yes,NaN
4,S005,Vikram Singh,Male,17,11th,Science,Jaipur,80,90,88,85,70,NaN,NaN,20,Yes,Post-Graduate,Yes,No,NaN
5,S006,Ananya Iyer,Female,18,12th,Science,Bangalore,98,95,92,88,96,NaN,NaN,22,Yes,Post-Graduate,Yes,Yes,NaN
6,S007,Karan Nair,Male,15,9th,Arts,Kochi,60,50,55,70,65,NaN,NaN,8,No,High School,No,No,NaN
7,S008,Divya Reddy,Female,16,10th,Commerce,Hyderabad,88,68,75,72,80,NaN,NaN,13,Yes,Graduate,No,Yes,NaN
8,S009,Arjun Joshi,Male,17,11th,Science,Pune,70,78,74,70,65,NaN,NaN,15,Yes,Graduate,No,No,NaN
9,S010,Meera Pillai,Female,18,12th,Commerce,Trivandrum,93,60,85,78,88,NaN,NaN,16,Yes,Post-Graduate,Yes,Yes,NaN
10,S011,Siddharth Roy,Male,16,10th,Science,Kolkata,82,80,76,74,79,NaN,NaN,17,Yes,Graduate,No,Yes,NaN
11,S012,Lakshmi Rao,Female,15,9th,Arts,Chennai,78,55,60,80,75,NaN,NaN,11,No,High School,No,No,NaN
12,S013,Nikhil Desai,Male,17,11th,Commerce,Surat,65,62,70,58,66,NaN,NaN,9,No,High School,No,No,NaN
13,S014,Pooja Verma,Female,18,12th,Science,Lucknow,90,88,84,90,86,NaN,NaN,19,Yes,Post-Graduate,Yes,Yes,NaN
14,S015,Rahul Gupta,Male,16,10th,Arts,Kanpur,55,48,52,65,58,NaN,NaN,7,No,High School,No,No,NaN
15,S016,Ishaan Malhotra,Male,17,11th,Science,Delhi,85,92,89,84,80,NaN,NaN,21,Yes,Post-Graduate,Yes,Yes,NaN
16,S017,Tanvi Bhatt,Female,15,9th,Commerce,Vadodara,72,60,68,62,70,NaN,NaN,10,Yes,Graduate,No,No,NaN
17,S018,Aditya Pandey,Male,18,12th,Science,Varanasi,68,74,70,65,72,NaN,NaN,14,No,Graduate,No,Yes,NaN
18,S019,Ritu Saxena,Female,16,10th,Arts,Agra,84,58,62,82,80,NaN,NaN,12,Yes,High School,No,Yes,NaN
19,S020,Manish Tiwari,Male,17,11th,Commerce,Bhopal,77,65,72,60,75,NaN,NaN,13,No,Graduate,No,No,NaN
20,S021,Kavya Menon,Female,18,12th,Science,Coimbatore,96,94,91,89,95,NaN,NaN,23,Yes,Post-Graduate,Yes,Yes,NaN
21,S022,Harsh Agarwal,Male,15,9th,Arts,Indore,58,45,50,68,55,NaN,NaN,6,No,High School,No,No,NaN
22,S023,Swati Mishra,Female,16,10th,Science,Nagpur,81,79,77,75,82,NaN,NaN,16,Yes,Graduate,Yes,No,NaN
23,S024,Varun Kapoor,Male,17,11th,Commerce,Chandigarh,74,66,71,63,76,NaN,NaN,12,Yes,Graduate,No,Yes,NaN
24,S025,Deepa Nambiar,Female,18,12th,Arts,Kochi,89,62,70,92,88,NaN,NaN,15,Yes,Post-Graduate,No,Yes,NaN
25,S026,Akash Srivastava,Male,16,10th,Science,Allahabad,66,72,68,64,70,NaN,NaN,11,No,Graduate,No,No,NaN
26,S027,Shruti Kulkarni,Female,15,9th,Commerce,Nashik,76,58,65,60,72,NaN,NaN,9,Yes,High School,No,No,NaN
27,S028,Piyush Bansal,Male,17,11th,Science,Faridabad,83,86,84,80,82,NaN,NaN,18,Yes,Graduate,Yes,Yes,NaN
28,S029,Neha Chaudhary,Female,18,12th,Arts,Meerut,91,55,68,94,90,NaN,NaN,14,No,Post-Graduate,Yes,Yes,NaN
29,S030,Sameer Khan,Male,16,10th,Commerce,Lucknow,70,60,68,58,72,NaN,NaN,10,No,High School,No,No,NaN
30,S031,Anjali Subramaniam,Female,17,11th,Science,Madurai,88,90,87,85,89,NaN,NaN,20,Yes,Post-Graduate,Yes,Yes,NaN
31,S032,Rajesh Naidu,Male,15,9th,Arts,Vizag,62,50,55,72,60,NaN,NaN,8,No,High School,No,No,NaN
32,S033,Preeti Sharma,Female,18,12th,Commerce,Gurgaon,94,70,82,75,92,NaN,NaN,16,Yes,Graduate,Yes,Yes,NaN
33,S034,Yash Chauhan,Male,16,10th,Science,Noida,79,82,78,76,80,NaN,NaN,15,Yes,Graduate,No,Yes,NaN
34,S035,Bhavna Soni,Female,17,11th,Arts,Rajkot,85,56,65,90,84,NaN,NaN,13,Yes,High School,No,Yes,NaN
35,S036,Kartik Bajaj,Male,18,12th,Science,Amritsar,73,76,74,70,75,NaN,NaN,12,No,Graduate,No,No,NaN
36,S037,Riya Jain,Female,15,9th,Commerce,Jodhpur,80,62,72,65,78,NaN,NaN,11,Yes,Graduate,No,No,NaN
37,S038,Suresh Pillai,Male,16,10th,Arts,Thrissur,67,48,54,74,65,NaN,NaN,9,No,High School,No,No,NaN
38,S039,Nandini Ghosh,Female,17,11th,Science,Kolkata,92,88,86,84,91,NaN,NaN,21,Yes,Post-Graduate,Yes,Yes,NaN
39,S040,Abhishek Pandey,Male,18,12th,Commerce,Patna,76,64,72,60,78,NaN,NaN,13,No,Graduate,No,Yes,NaN

In [10]:
df.describe()

,Age,Attendance_%,Math_Score,Science_Score,English_Score,History_Score,Avg_Score,Grade,Study_Hours/Week,Pass/Fail
count,40.000000,40.000000,40.00000,40.000000,40.000000,40.00000,0.0,0.0,40.000000,0.0
mean,16.575000,79.350000,69.15000,72.600000,74.500000,77.60000,NaN,NaN,13.825000,NaN
std,1.083383,11.308155,14.57351,11.265559,10.926327,10.18999,NaN,NaN,4.384632,NaN
min,15.000000,55.000000,45.00000,50.000000,58.000000,55.00000,NaN,NaN,6.000000,NaN
25%,16.000000,71.500000,58.00000,67.250000,65.000000,71.50000,NaN,NaN,10.750000,NaN
50%,17.000000,80.000000,65.50000,72.000000,74.000000,78.00000,NaN,NaN,13.000000,NaN
75%,17.250000,88.250000,80.50000,82.500000,84.250000,85.25000,NaN,NaN,16.250000,NaN
max,18.000000,98.000000,95.00000,92.000000,94.000000,96.00000,NaN,NaN,23.000000,NaN

In [11]:
df["Avg_Score"] = (
    df["Math_Score"] +
    df["Science_Score"] +
    df["English_Score"] +
    df["History_Score"]
) / 4

df["Avg_Score"]

0     85.25
1     76.25
2     66.75
3     72.50
4     83.25
5     92.75
6     60.00
7     73.75
8     71.75
9     77.75
10    77.25
11    67.50
12    64.00
13    87.00
14    55.75
15    86.25
16    65.00
17    70.25
18    70.50
19    68.00
20    92.25
21    54.50
22    78.25
23    69.00
24    78.00
25    68.50
26    63.75
27    83.00
28    76.75
29    64.50
30    87.75
31    59.25
32    79.75
33    79.00
34    73.75
35    73.75
36    69.25
37    60.25
38    87.25
39    68.50
Name: Avg_Score, dtype: float64

In [17]:
def attendance(x):
    if x >= 90:
        return "Excellent"
    elif x >= 75:
        return "Good"
    else:
        return "Poor"

df["Attendance_Category"] = df["Attendance_%"].apply(attendance)
df["Attendance_Category"]
df

,Student_ID,Student_Name,Gender,Age,Grade_Level,Department,City,Attendance_%,Math_Score,Science_Score,...,History_Score,Avg_Score,Grade,Study_Hours/Week,Internet_Access,Parent_Education,Scholarship,Extracurricular,Pass/Fail,Attendance_Category
0,S001,Aarav Kumar,Male,16,10th,Science,Chennai,92,88,85,...,78,85.25,B,18,Yes,Graduate,Yes,Yes,NaN,Excellent
1,S002,Priya Sharma,Female,17,11th,Commerce,Mumbai,87,72,80,...,85,76.25,C,14,Yes,Post-Graduate,No,No,NaN,Good
2,S003,Rohit Mehta,Male,15,9th,Science,Delhi,75,65,70,...,72,66.75,D,10,No,High School,No,Yes,NaN,Good
3,S004,Sneha Patel,Female,16,10th,Arts,Ahmedabad,95,55,60,...,90,72.50,C,12,Yes,Graduate,Yes,Yes,NaN,Excellent
4,S005,Vikram Singh,Male,17,11th,Science,Jaipur,80,90,88,...,70,83.25,B,20,Yes,Post-Graduate,Yes,No,NaN,Good
5,S006,Ananya Iyer,Female,18,12th,Science,Bangalore,98,95,92,...,96,92.75,A,22,Yes,Post-Graduate,Yes,Yes,NaN,Excellent
6,S007,Karan Nair,Male,15,9th,Arts,Kochi,60,50,55,...,65,60.00,D,8,No,High School,No,No,NaN,Poor
7,S008,Divya Reddy,Female,16,10th,Commerce,Hyderabad,88,68,75,...,80,73.75,C,13,Yes,Graduate,No,Yes,NaN,Good
8,S009,Arjun Joshi,Male,17,11th,Science,Pune,70,78,74,...,65,71.75,C,15,Yes,Graduate,No,No,NaN,Poor
9,S010,Meera Pillai,Female,18,12th,Commerce,Trivandrum,93,60,85,...,88,77.75,C,16,Yes,Post-Graduate,Yes,Yes,NaN,Excellent
10,S011,Siddharth Roy,Male,16,10th,Science,Kolkata,82,80,76,...,79,77.25,C,17,Yes,Graduate,No,Yes,NaN,Good
11,S012,Lakshmi Rao,Female,15,9th,Arts,Chennai,78,55,60,...,75,67.50,D,11,No,High School,No,No,NaN,Good
12,S013,Nikhil Desai,Male,17,11th,Commerce,Surat,65,62,70,...,66,64.00,D,9,No,High School,No,No,NaN,Poor
13,S014,Pooja Verma,Female,18,12th,Science,Lucknow,90,88,84,...,86,87.00,B,19,Yes,Post-Graduate,Yes,Yes,NaN,Excellent
14,S015,Rahul Gupta,Male,16,10th,Arts,Kanpur,55,48,52,...,58,55.75,F,7,No,High School,No,No,NaN,Poor
15,S016,Ishaan Malhotra,Male,17,11th,Science,Delhi,85,92,89,...,80,86.25,B,21,Yes,Post-Graduate,Yes,Yes,NaN,Good
16,S017,Tanvi Bhatt,Female,15,9th,Commerce,Vadodara,72,60,68,...,70,65.00,D,10,Yes,Graduate,No,No,NaN,Poor
17,S018,Aditya Pandey,Male,18,12th,Science,Varanasi,68,74,70,...,72,70.25,C,14,No,Graduate,No,Yes,NaN,Poor
18,S019,Ritu Saxena,Female,16,10th,Arts,Agra,84,58,62,...,80,70.50,C,12,Yes,High School,No,Yes,NaN,Good
19,S020,Manish Tiwari,Male,17,11th,Commerce,Bhopal,77,65,72,...,75,68.00,D,13,No,Graduate,No,No,NaN,Good
20,S021,Kavya Menon,Female,18,12th,Science,Coimbatore,96,94,91,...,95,92.25,A,23,Yes,Post-Graduate,Yes,Yes,NaN,Excellent
21,S022,Harsh Agarwal,Male,15,9th,Arts,Indore,58,45,50,...,55,54.50,F,6,No,High School,No,No,NaN,Poor
22,S023,Swati Mishra,Female,16,10th,Science,Nagpur,81,79,77,...,82,78.25,C,16,Yes,Graduate,Yes,No,NaN,Good
23,S024,Varun Kapoor,Male,17,11th,Commerce,Chandigarh,74,66,71,...,76,69.00,D,12,Yes,Graduate,No,Yes,NaN,Poor
24,S025,Deepa Nambiar,Female,18,12th,Arts,Kochi,89,62,70,...,88,78.00,C,15,Yes,Post-Graduate,No,Yes,NaN,Good
25,S026,Akash Srivastava,Male,16,10th,Science,Allahabad,66,72,68,...,70,68.50,D,11,No,Graduate,No,No,NaN,Poor
26,S027,Shruti Kulkarni,Female,15,9th,Commerce,Nashik,76,58,65,...,72,63.75,D,9,Yes,High School,No,No,NaN,Good
27,S028,Piyush Bansal,Male,17,11th,Science,Faridabad,83,86,84,...,82,83.00,B,18,Yes,Graduate,Yes,Yes,NaN,Good
28,S029,Neha Chaudhary,Female,18,12th,Arts,Meerut,91,55,68,...,90,76.75,C,14,No,Post-Graduate,Yes,Yes,NaN,Excellent
29,S030,Sameer Khan,Male,16,10th,Commerce,Lucknow,70,60,68,...,72,64.50,D,10,No,High School,No,No,NaN,Poor
30,S031,Anjali Subramaniam,Female,17,11th,Science,Madurai,88,90,87,...,89,87.75,B,20,Yes,Post-Graduate,Yes,Yes,NaN,Good
31,S032,Rajesh Naidu,Male,15,9th,Arts,Vizag,62,50,55,...,60,59.25,F,8,No,High School,No,No,NaN,Poor
32,S033,Preeti Sharma,Female,18,12th,Commerce,Gurgaon,94,70,82,...,92,79.75,C,16,Yes,Graduate,Yes,Yes,NaN,Excellent
33,S034,Yash Chauhan,Male,16,10th,Science,Noida,79,82,78,...,80,79.00,C,15,Yes,Graduate,No,Yes,NaN,Good
34,S035,Bhavna Soni,Female,17,11th,Arts,Rajkot,85,56,65,...,84,73.75,C,13,Yes,High School,No,Yes,NaN,Good
35,S036,Kartik Bajaj,Male,18,12th,Science,Amritsar,73,76,74,...,75,73.75,C,12,No,Graduate,No,No,NaN,Poor
36,S037,Riya Jain,Female,15,9th,Commerce,Jodhpur,80,62,72,...,78,69.25,D,11,Yes,Graduate,No,No,NaN,Good
37,S038,Suresh Pillai,Male,16,10th,Arts,Thrissur,67,48,54,...,65,60.25,D,9,No,High School,No,No,NaN,Poor
38,S039,Nandini Ghosh,Female,17,11th,Science,Kolkata,92,88,86,...,91,87.25,B,21,Yes,Post-Graduate,Yes,Yes,NaN,Excellent
39,S040,Abhishek Pandey,Male,18,12th,Commerce,Patna,76,64,72,...,78,68.50,D,13,No,Graduate,No,Yes,NaN,Good

In [19]:
df["Pass/Fail"] = df["Avg_Score"].apply(
    lambda x: "Pass" if x >= 50 else "Fail"
)
df

,Student_ID,Student_Name,Gender,Age,Grade_Level,Department,City,Attendance_%,Math_Score,Science_Score,...,History_Score,Avg_Score,Grade,Study_Hours/Week,Internet_Access,Parent_Education,Scholarship,Extracurricular,Pass/Fail,Attendance_Category
0,S001,Aarav Kumar,Male,16,10th,Science,Chennai,92,88,85,...,78,85.25,B,18,Yes,Graduate,Yes,Yes,Pass,Excellent
1,S002,Priya Sharma,Female,17,11th,Commerce,Mumbai,87,72,80,...,85,76.25,C,14,Yes,Post-Graduate,No,No,Pass,Good
2,S003,Rohit Mehta,Male,15,9th,Science,Delhi,75,65,70,...,72,66.75,D,10,No,High School,No,Yes,Pass,Good
3,S004,Sneha Patel,Female,16,10th,Arts,Ahmedabad,95,55,60,...,90,72.50,C,12,Yes,Graduate,Yes,Yes,Pass,Excellent
4,S005,Vikram Singh,Male,17,11th,Science,Jaipur,80,90,88,...,70,83.25,B,20,Yes,Post-Graduate,Yes,No,Pass,Good
5,S006,Ananya Iyer,Female,18,12th,Science,Bangalore,98,95,92,...,96,92.75,A,22,Yes,Post-Graduate,Yes,Yes,Pass,Excellent
6,S007,Karan Nair,Male,15,9th,Arts,Kochi,60,50,55,...,65,60.00,D,8,No,High School,No,No,Pass,Poor
7,S008,Divya Reddy,Female,16,10th,Commerce,Hyderabad,88,68,75,...,80,73.75,C,13,Yes,Graduate,No,Yes,Pass,Good
8,S009,Arjun Joshi,Male,17,11th,Science,Pune,70,78,74,...,65,71.75,C,15,Yes,Graduate,No,No,Pass,Poor
9,S010,Meera Pillai,Female,18,12th,Commerce,Trivandrum,93,60,85,...,88,77.75,C,16,Yes,Post-Graduate,Yes,Yes,Pass,Excellent
10,S011,Siddharth Roy,Male,16,10th,Science,Kolkata,82,80,76,...,79,77.25,C,17,Yes,Graduate,No,Yes,Pass,Good
11,S012,Lakshmi Rao,Female,15,9th,Arts,Chennai,78,55,60,...,75,67.50,D,11,No,High School,No,No,Pass,Good
12,S013,Nikhil Desai,Male,17,11th,Commerce,Surat,65,62,70,...,66,64.00,D,9,No,High School,No,No,Pass,Poor
13,S014,Pooja Verma,Female,18,12th,Science,Lucknow,90,88,84,...,86,87.00,B,19,Yes,Post-Graduate,Yes,Yes,Pass,Excellent
14,S015,Rahul Gupta,Male,16,10th,Arts,Kanpur,55,48,52,...,58,55.75,F,7,No,High School,No,No,Pass,Poor
15,S016,Ishaan Malhotra,Male,17,11th,Science,Delhi,85,92,89,...,80,86.25,B,21,Yes,Post-Graduate,Yes,Yes,Pass,Good
16,S017,Tanvi Bhatt,Female,15,9th,Commerce,Vadodara,72,60,68,...,70,65.00,D,10,Yes,Graduate,No,No,Pass,Poor
17,S018,Aditya Pandey,Male,18,12th,Science,Varanasi,68,74,70,...,72,70.25,C,14,No,Graduate,No,Yes,Pass,Poor
18,S019,Ritu Saxena,Female,16,10th,Arts,Agra,84,58,62,...,80,70.50,C,12,Yes,High School,No,Yes,Pass,Good
19,S020,Manish Tiwari,Male,17,11th,Commerce,Bhopal,77,65,72,...,75,68.00,D,13,No,Graduate,No,No,Pass,Good
20,S021,Kavya Menon,Female,18,12th,Science,Coimbatore,96,94,91,...,95,92.25,A,23,Yes,Post-Graduate,Yes,Yes,Pass,Excellent
21,S022,Harsh Agarwal,Male,15,9th,Arts,Indore,58,45,50,...,55,54.50,F,6,No,High School,No,No,Pass,Poor
22,S023,Swati Mishra,Female,16,10th,Science,Nagpur,81,79,77,...,82,78.25,C,16,Yes,Graduate,Yes,No,Pass,Good
23,S024,Varun Kapoor,Male,17,11th,Commerce,Chandigarh,74,66,71,...,76,69.00,D,12,Yes,Graduate,No,Yes,Pass,Poor
24,S025,Deepa Nambiar,Female,18,12th,Arts,Kochi,89,62,70,...,88,78.00,C,15,Yes,Post-Graduate,No,Yes,Pass,Good
25,S026,Akash Srivastava,Male,16,10th,Science,Allahabad,66,72,68,...,70,68.50,D,11,No,Graduate,No,No,Pass,Poor
26,S027,Shruti Kulkarni,Female,15,9th,Commerce,Nashik,76,58,65,...,72,63.75,D,9,Yes,High School,No,No,Pass,Good
27,S028,Piyush Bansal,Male,17,11th,Science,Faridabad,83,86,84,...,82,83.00,B,18,Yes,Graduate,Yes,Yes,Pass,Good
28,S029,Neha Chaudhary,Female,18,12th,Arts,Meerut,91,55,68,...,90,76.75,C,14,No,Post-Graduate,Yes,Yes,Pass,Excellent
29,S030,Sameer Khan,Male,16,10th,Commerce,Lucknow,70,60,68,...,72,64.50,D,10,No,High School,No,No,Pass,Poor
30,S031,Anjali Subramaniam,Female,17,11th,Science,Madurai,88,90,87,...,89,87.75,B,20,Yes,Post-Graduate,Yes,Yes,Pass,Good
31,S032,Rajesh Naidu,Male,15,9th,Arts,Vizag,62,50,55,...,60,59.25,F,8,No,High School,No,No,Pass,Poor
32,S033,Preeti Sharma,Female,18,12th,Commerce,Gurgaon,94,70,82,...,92,79.75,C,16,Yes,Graduate,Yes,Yes,Pass,Excellent
33,S034,Yash Chauhan,Male,16,10th,Science,Noida,79,82,78,...,80,79.00,C,15,Yes,Graduate,No,Yes,Pass,Good
34,S035,Bhavna Soni,Female,17,11th,Arts,Rajkot,85,56,65,...,84,73.75,C,13,Yes,High School,No,Yes,Pass,Good
35,S036,Kartik Bajaj,Male,18,12th,Science,Amritsar,73,76,74,...,75,73.75,C,12,No,Graduate,No,No,Pass,Poor
36,S037,Riya Jain,Female,15,9th,Commerce,Jodhpur,80,62,72,...,78,69.25,D,11,Yes,Graduate,No,No,Pass,Good
37,S038,Suresh Pillai,Male,16,10th,Arts,Thrissur,67,48,54,...,65,60.25,D,9,No,High School,No,No,Pass,Poor
38,S039,Nandini Ghosh,Female,17,11th,Science,Kolkata,92,88,86,...,91,87.25,B,21,Yes,Post-Graduate,Yes,Yes,Pass,Excellent
39,S040,Abhishek Pandey,Male,18,12th,Commerce,Patna,76,64,72,...,78,68.50,D,13,No,Graduate,No,Yes,Pass,Good

In [27]:
df.to_csv("D:\\edge downlode\\cleaned_education_dataset.csv")

In [21]:
from sqlalchemy import create_engine
engine = create_engine(
    "mysql+pymysql://root:@localhost:3306/education_db"
)
df.to_sql(
    name="education_dataset",
    con=engine,
    if_exists="replace",
    index=False
)

40